using RamOcr;
using System.Reflection;
static void Require(bool value, string message) { if (!value) throw new InvalidOperationException(message); }
var trigger = new OcrTrigger { Text = "banner", TextMode = TextMatchMode.Contains };
Require(TextMatcher.Evaluate("A BANNER appeared", trigger).Matches, "Text matching failed.");
var color = new OcrTrigger { Color = new Rgba32(255, 0, 0, 255), Tolerance = 0, RequiredMatchPercentage = 1 };
Require(ColorMatcher.Evaluate([new Rgba32(255, 0, 0, 255)], color).Matches, "Color matching failed.");
var fired = 0; var coordinator = new TriggerCoordinator(_ => { fired++; return Task.CompletedTask; });
await coordinator.ObserveAsync(trigger, new(true, 1, "match"), DateTime.UtcNow);
await coordinator.ObserveAsync(trigger, new(true, 1, "match"), DateTime.UtcNow.AddMilliseconds(600));
Require(fired == 1, "Trigger debounce did not fire once.");
Require(!CaptureAvailability.CanCapture(true, true), "Minimized capture was not suspended.");
var tokenPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid() + ".token");
await File.WriteAllTextAsync(tokenPath, "test-token");
var launchClient = PluginClient.FromArgs(["--ram-plugin", "--pipe", "test-pipe", "--token-file", tokenPath, "--plugin-id", "io.github.codysimonds65.ram.ocr", "--data", "test-data"]);
Require(launchClient is not null && !File.Exists(tokenPath), "Plugin launch arguments did not preserve the host pipe and token-file values.");
var pluginIdField = typeof(PluginClient).GetField("_pluginId", BindingFlags.Instance | BindingFlags.NonPublic);
var tokenField = typeof(PluginClient).GetField("_token", BindingFlags.Instance | BindingFlags.NonPublic);
Require((string?)pluginIdField?.GetValue(launchClient) == "io.github.codysimonds65.ram.ocr", "Plugin launch arguments did not preserve the plugin ID.");
Require((string?)tokenField?.GetValue(launchClient) == "test-token", "Plugin launch arguments did not preserve the token.");
var parseMethod = typeof(PluginClient).GetMethod("TryParseArgs", BindingFlags.Static | BindingFlags.NonPublic);
var parseArguments = new object?[] { new[] { "--ram-plugin", "--pipe", "test-pipe", "--plugin-id", "io.github.codysimonds65.ram.ocr", "--data", "test-data" }, null };
Require((bool?)parseMethod?.Invoke(null, parseArguments) == true, "Valid launch arguments were not parsed.");
var parsedArguments = parseArguments[1] as IReadOnlyDictionary<string, string>;
Require(parsedArguments is not null && parsedArguments["pipe"] == "test-pipe" && parsedArguments["data"] == "test-data", "Parsed pipe or data values were not preserved.");
await launchClient!.DisposeAsync();
Require(PluginClient.FromArgs(["--ram-plugin", "--pipe"]) is null, "A missing pipe value was accepted.");
Require(PluginClient.FromArgs(["--ram-plugin", "--pipe", "", "--plugin-id", "io.github.codysimonds65.ram.ocr", "--token", "test-token"]) is null, "An empty pipe value was accepted.");
Require(PluginClient.FromArgs(["--ram-plugin", "--pipe", "test-pipe", "--plugin-id"]) is null, "A missing plugin ID value was accepted.");
Require(PluginClient.FromArgs(["--ram-plugin", "--pipe", "test-pipe", "--plugin-id", "", "--token", "test-token"]) is null, "An empty plugin ID was accepted.");
Require(PluginClient.FromArgs(["--ram-plugin", "--pipe", "test-pipe", "--plugin-id", "io.github.codysimonds65.ram.ocr", "--token", ""]) is null, "An empty inline token was accepted.");
Require(PluginClient.FromArgs(["--ram-plugin", "--pipe", "test-pipe", "--plugin-id", "io.github.codysimonds65.ram.ocr", "--token-file"]) is null, "A missing token-file value was accepted.");
Require(PluginClient.FromArgs(["--ram-plugin", "--pipe", "test-pipe", "--plugin-id", "io.github.codysimonds65.ram.ocr", "--token-file", Path.Combine(Path.GetTempPath(), Guid.NewGuid() + ".missing")]) is null, "A missing token file was not rejected safely.");
var emptyTokenPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid() + ".empty-token");
await File.WriteAllTextAsync(emptyTokenPath, "");
Require(PluginClient.FromArgs(["--ram-plugin", "--pipe", "test-pipe", "--plugin-id", "io.github.codysimonds65.ram.ocr", "--token-file", emptyTokenPath]) is null, "An empty token file was accepted.");
var conflictTokenPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid() + ".conflict-token");
await File.WriteAllTextAsync(conflictTokenPath, "file-token");
Require(PluginClient.FromArgs(["--ram-plugin", "--pipe", "test-pipe", "--plugin-id", "io.github.codysimonds65.ram.ocr", "--token", "inline-token", "--token-file", conflictTokenPath]) is null, "Conflicting credential sources were accepted.");
if (File.Exists(conflictTokenPath)) File.Delete(conflictTokenPath);
Require(PluginClient.FromArgs(["--ram-plugin", "--pipe", "one", "--pipe", "two", "--plugin-id", "io.github.codysimonds65.ram.ocr", "--token", "test-token"]) is null, "Duplicate launch options were accepted.");
Console.WriteLine("RAM OCR tests passed.");
